### ISSUE TITLE
Dye sheep

### ISSUE THREAD

**Issue by LuckyTurtle1313** [Eltrut-Co/Flamboyant-Recrafted#11]
This might not be an issue but I can't dye sheep with the new dyes.

**Comment by PercyJames** [comment]
I'm hoping they're working on shulker boxes. also adding the new dye colors to the jeb_ sheep color cycle

**Comment by EltrutLikes** [comment]
This is not currently implemented in the mod as I am trying to figure out the best way to approach this. Additionally, adding the new colors to the jeb_ sheep cycle is not planned but we will see if it is at all possible.
