### ISSUE TITLE
[Suggestion] Ports for modern Minecraft versions

### ISSUE THREAD

**Issue by COMBOhrenovke** [Eltrut-Co/Flamboyant-Recrafted#15]
Port for 1.18.2 version, as that's where most modding occurs currently and for 1.19.1 as that is the most recent version.

There are stable releases of Forge for both now, so there shouldn't be many issues in further Forge updates.
I saw that other two mods, Lepton and Addendum had 1.18.2 versions and was puzzled why this one doesn't.

If the mod is abandoned, please put a note on webpage of the mod or here on github.

**Comment by EltrutLikes** [comment]
Porting for 1.18.2 has begun, the only reason it hasn't been finished is because block entity renderers changed and I haven't had the time to figure out how it works now.
